version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - HTTPS_METHOD=noredirect
    volumes:
      - .:/usr/share/nginx/html
